# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-30 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20180530_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
